"""empty message

Revision ID: 3a190600d3b9
Revises: 50c7b4de8613
Create Date: 2021-12-05 15:15:25.114346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a190600d3b9'
down_revision = '50c7b4de8613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('price', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
