"""empty message

Revision ID: 50c7b4de8613
Revises: ebc79b45c0bb
Create Date: 2021-12-05 00:07:38.980960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c7b4de8613'
down_revision = 'ebc79b45c0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('user_phone_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'user_phone_number')
    # ### end Alembic commands ###
