"""empty message

Revision ID: ebc79b45c0bb
Revises: 9dc45e35a21f
Create Date: 2021-12-04 20:26:32.131881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ebc79b45c0bb'
down_revision = '9dc45e35a21f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'user_id')
    )
    op.create_table('ad_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'ad_id')
    )
    op.drop_table('association')
    op.add_column('ads', sa.Column('text_description', sa.Text(), nullable=False))
    op.add_column('ads', sa.Column('location', sa.String(length=100), nullable=False))
    op.add_column('ads', sa.Column('price', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'price')
    op.drop_column('ads', 'location')
    op.drop_column('ads', 'text_description')
    op.create_table('association',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='association_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='association_ibfk_2'),
    sa.PrimaryKeyConstraint('role_id', 'user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ad_category')
    op.drop_table('user_role')
    op.drop_table('categories')
    # ### end Alembic commands ###
